version: 2

defaults: &defaults
  working_directory: ~/package
  docker:
    - image: circleci/node:8.9.1

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install
      - run:
          name: Run tests
          command: yarn test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/package
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/package/.npmrc
      - run:
          name: Publish package
          command: yarn publish

workflows:
  version: 2
  testing-build:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
